import { BlockShape, BlockId } from '../types/block';

export const ALL_BLOCKS: readonly BlockShape[] = [
  {
    id: 'B01',
    name: '単体',
    nameEn: 'Single',
    cells: [{ q: 0, r: 0 }],
    size: 1,
    rarity: 'common',
    unlockWins: 0,
    color: '#4CAF50',
    description: '1マスだけ。確実に置ける万能ブロック。',
  },
  {
    id: 'B02',
    name: '双子',
    nameEn: 'Twin',
    cells: [{ q: 0, r: 0 }, { q: 1, r: 0 }],
    size: 2,
    rarity: 'common',
    unlockWins: 0,
    color: '#2196F3',
    description: '2マス横並び。序盤の拡張に最適。',
  },
  {
    id: 'B03',
    name: '直線',
    nameEn: 'Line',
    cells: [{ q: -1, r: 0 }, { q: 0, r: 0 }, { q: 1, r: 0 }],
    size: 3,
    rarity: 'common',
    unlockWins: 0,
    color: '#FF9800',
    description: '3マス直線。長く伸ばして挟み込め。',
  },
  {
    id: 'B04',
    name: 'L字',
    nameEn: 'L-Shape',
    cells: [{ q: 0, r: 0 }, { q: 1, r: 0 }, { q: 0, r: 1 }],
    size: 3,
    rarity: 'common',
    unlockWins: 0,
    color: '#9C27B0',
    description: 'L字型。角を曲がって配置できる。',
  },
  {
    id: 'B05',
    name: 'くの字',
    nameEn: 'V-Shape',
    cells: [{ q: 0, r: -1 }, { q: 0, r: 0 }, { q: -1, r: 1 }],
    size: 3,
    rarity: 'common',
    unlockWins: 0,
    color: '#F44336',
    description: 'くの字型。ジグザグに陣地を広げる。',
  },
  {
    id: 'B06',
    name: 'Z字',
    nameEn: 'Z-Shape',
    cells: [{ q: 0, r: -1 }, { q: 0, r: 0 }, { q: 1, r: 0 }, { q: 1, r: 1 }],
    size: 4,
    rarity: 'rare',
    unlockWins: 5,
    color: '#00BCD4',
    description: 'Z字型4マス。大きく陣地を広げる。',
  },
  {
    id: 'B07',
    name: 'S字',
    nameEn: 'S-Shape',
    cells: [{ q: 1, r: -1 }, { q: 0, r: 0 }, { q: 1, r: 0 }, { q: 0, r: 1 }],
    size: 4,
    rarity: 'rare',
    unlockWins: 5,
    color: '#E91E63',
    description: 'S字型4マス。Z字の鏡像。',
  },
  {
    id: 'B08',
    name: '三角',
    nameEn: 'Triangle',
    cells: [{ q: 0, r: -1 }, { q: -1, r: 0 }, { q: 0, r: 0 }, { q: 1, r: 0 }],
    size: 4,
    rarity: 'rare',
    unlockWins: 7,
    color: '#FF5722',
    description: '三角形4マス。面で押し広げる。',
  },
  {
    id: 'B09',
    name: '四角',
    nameEn: 'Diamond',
    cells: [
      { q: 0, r: -1 }, { q: 1, r: -1 },
      { q: 0, r: 0 }, { q: 1, r: 0 },
    ],
    size: 4,
    rarity: 'rare',
    unlockWins: 10,
    color: '#795548',
    description: 'ひし形4マス。密集した陣地を作る。',
  },
  {
    id: 'B10',
    name: '矢印',
    nameEn: 'Arrow',
    cells: [
      { q: 0, r: -1 },
      { q: -1, r: 0 }, { q: 0, r: 0 }, { q: 1, r: 0 },
      { q: 0, r: 1 },
    ],
    size: 5,
    rarity: 'rare',
    unlockWins: 12,
    color: '#607D8B',
    description: '十字型5マス。全方向に影響力を持つ。',
  },
  {
    id: 'B11',
    name: '大L字',
    nameEn: 'Big L',
    cells: [
      { q: 0, r: -1 }, { q: 0, r: 0 },
      { q: 0, r: 1 }, { q: 1, r: 1 },
    ],
    size: 4,
    rarity: 'epic',
    unlockWins: 15,
    color: '#3F51B5',
    description: '大きなL字。遠くまで手が届く。',
  },
  {
    id: 'B12',
    name: 'T字',
    nameEn: 'T-Shape',
    cells: [
      { q: -1, r: 0 }, { q: 0, r: 0 }, { q: 1, r: 0 },
      { q: 0, r: 1 },
    ],
    size: 4,
    rarity: 'epic',
    unlockWins: 18,
    color: '#009688',
    description: 'T字型。攻めと守りの両方に使える。',
  },
  {
    id: 'B13',
    name: '稲妻',
    nameEn: 'Lightning',
    cells: [
      { q: -1, r: 0 }, { q: 0, r: 0 },
      { q: 0, r: 1 }, { q: 1, r: 1 },
      { q: 1, r: 2 },
    ],
    size: 5,
    rarity: 'epic',
    unlockWins: 20,
    color: '#FFC107',
    description: '稲妻型5マス。長く蛇行して配置。',
  },
  {
    id: 'B14',
    name: '花',
    nameEn: 'Flower',
    cells: [
      { q: 0, r: -1 }, { q: 1, r: -1 },
      { q: -1, r: 0 }, { q: 0, r: 0 }, { q: 1, r: 0 },
      { q: -1, r: 1 }, { q: 0, r: 1 },
    ],
    size: 7,
    rarity: 'legendary',
    unlockWins: 25,
    color: '#E040FB',
    description: '花型7マス。一撃で盤面を制圧する最強ブロック。',
  },
  {
    id: 'B15',
    name: 'リング',
    nameEn: 'Ring',
    cells: [
      { q: 0, r: -1 }, { q: 1, r: -1 },
      { q: -1, r: 0 }, { q: 1, r: 0 },
      { q: -1, r: 1 }, { q: 0, r: 1 },
    ],
    size: 6,
    rarity: 'legendary',
    unlockWins: 30,
    color: '#FFD700',
    description: 'リング型6マス。中央を空けて囲い込む戦術用。',
  },
] as const;

export const INITIAL_BLOCKS: readonly BlockShape[] = ALL_BLOCKS.filter(b => b.unlockWins === 0);

export function getBlockById(id: BlockId): BlockShape | undefined {
  return ALL_BLOCKS.find(b => b.id === id);
}

export function getUnlockableBlocks(wins: number): BlockShape[] {
  return [...ALL_BLOCKS].filter(b => b.unlockWins > 0 && b.unlockWins <= wins);
}
